import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { getPlan, getSubject } from '../api/client'
import Card from '../components/ui/Card'
import Button from '../components/ui/Button'
import Spinner from '../components/ui/Spinner'

export default function LearningPlan() {
  const { id } = useParams()
  const [plan, setPlan] = useState(null)
  const [subject, setSubject] = useState(null)
  const [loading, setLoading] = useState(true)
  const [notFound, setNotFound] = useState(false)

  useEffect(() => {
    Promise.all([getSubject(Number(id)), getPlan(Number(id))])
      .then(([s, p]) => {
        setSubject(s)
        setPlan(p)
      })
      .catch((e) => {
        if (e.status === 404) setNotFound(true)
      })
      .finally(() => setLoading(false))
  }, [id])

  if (loading) return <div className="flex justify-center pt-20"><Spinner size="lg" /></div>

  if (notFound || !plan) {
    return (
      <div className="max-w-xl space-y-4">
        <h1 className="text-2xl font-bold text-slate-100">Learning Plan</h1>
        <Card>
          <p className="text-slate-400">No learning plan generated yet for {subject?.name ?? 'this subject'}.</p>
          <p className="text-slate-500 text-sm mt-2">Plans are generated by the nightly batch process after material is uploaded and parsed.</p>
        </Card>
        <Link to="/subjects">
          <Button variant="ghost">← Back to Subjects</Button>
        </Link>
      </div>
    )
  }

  let planData = {}
  let deadlines = {}
  let focusAreas = []
  try { planData = typeof plan.plan_data === 'string' ? JSON.parse(plan.plan_data) : plan.plan_data } catch {}
  try { deadlines = typeof plan.deadlines === 'string' ? JSON.parse(plan.deadlines) : plan.deadlines } catch {}
  try { focusAreas = typeof plan.focus_areas === 'string' ? JSON.parse(plan.focus_areas) : plan.focus_areas } catch {}

  return (
    <div className="max-w-2xl space-y-6">
      <div className="flex items-center gap-3">
        <Link to="/subjects"><Button variant="ghost" size="sm">←</Button></Link>
        <h1 className="text-2xl font-bold text-slate-100">
          Learning Plan: {subject?.name}
        </h1>
      </div>

      {focusAreas?.length > 0 && (
        <Card>
          <h2 className="text-slate-300 font-semibold mb-3">Focus Areas</h2>
          <ul className="space-y-1">
            {focusAreas.map((area, i) => (
              <li key={i} className="text-slate-400 text-sm flex gap-2">
                <span className="text-forge-400">→</span>{area}
              </li>
            ))}
          </ul>
        </Card>
      )}

      <Card>
        <h2 className="text-slate-300 font-semibold mb-3">Plan</h2>
        <pre className="text-slate-400 text-sm whitespace-pre-wrap">{
          typeof planData === 'string' ? planData : JSON.stringify(planData, null, 2)
        }</pre>
      </Card>

      <p className="text-slate-600 text-xs">
        Last updated: {new Date(plan.generated_at).toLocaleString()}
      </p>
    </div>
  )
}
